version: '2'
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    image: keboola/sandboxes-api-php-client
    command: composer test
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - API_URL=http://sandboxes-api:8080
      - AWS_ACCESS_KEY_ID=accessKey
      - AWS_SECRET_ACCESS_KEY=secretKey
      - DYNAMO_ENDPOINT=http://localstack:4569
      - DYNAMO_TABLE_SANDBOXES=sandboxes
      - DYNAMO_TABLE_RUNS=runs
      - KBC_URL=https://connection.keboola.com
      - KBC_STORAGE_TOKEN
      - KBC_MANAGE_TOKEN
    depends_on:
      - sandboxes-api

  sandboxes-api:
    image: keboola.azurecr.io/sandboxes-api
    command: bash -c "yarn start"
    ports:
      - 8080:8080
    environment:
      - AWS_ACCESS_KEY_ID=accessKey
      - AWS_SECRET_ACCESS_KEY=secretKey
      - REGION=local
      - DYNAMO_ENDPOINT=http://localstack:4569
      - DYNAMO_TABLE_SANDBOXES=sandboxes
      - DYNAMO_TABLE_RUNS=runs
      - KBC_URL=https://connection.keboola.com
      - API_URL=http://sandboxes-api:8080
      - PROVIDER=aws
      - STAGE=dev
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:0.11.4
    environment:
      - SERVICES=dynamodb
      - DEBUG=1

