version: '2'
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    image: keboola/sandboxes-api-php-client
    command: composer test
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - API_URL=http://sandboxes-api:8080
      - KBC_URL=https://connection.keboola.com
      - KMS_ENDPOINT=http://localstack:4566
      - KBC_STORAGE_TOKEN
      - KBC_MANAGE_TOKEN
    depends_on:
      - sandboxes-api

  sandboxes-api:
    image: keboola.azurecr.io/sandboxes-api:latest
    command: bash -c "yarn start"
    ports:
      - 8080:8080
    environment:
      - API_URL=http://sandboxes-api:8080
      - AZURE_CLIENT_ID
      - AZURE_CLIENT_SECRET
      - AZURE_TENANT_ID
      - COSMOS_DB_ID=sandboxes-api
      - COSMOS_ENDPOINT
      - COSMOS_KEY
      - KBC_URL=https://connection.keboola.com
      - KEYVAULT_KEY_NAME=sandboxes-api-key
      - KEYVAULT_VAULT_NAME
      - PROVIDER=azure
      - STAGE=dev

