name: "Build"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - uses: azure/docker-login@v1
        with:
          login-server: keboola.azurecr.io
          username: ${{ secrets.ACR_PULL_USERNAME }}
          password: ${{ secrets.ACR_PULL_PASSWORD }}

      - run: docker pull localstack/localstack:0.11.4
      - run: docker pull waisbrot/wait
      - run: docker pull keboola.azurecr.io/sandboxes-api
      - run: docker build -t keboola/sandboxes-api-php-client .

      - run: |
          docker run -d --rm --network host -p4569:4569 \
          -e SERVICES=dynamodb \
          -e DEBUG=1 \
          localstack/localstack:0.11.4
      - run: |
          docker run --rm --network host \
          -e TARGETS=localhost:4569 \
          -e TIMEOUT=60 \
          waisbrot/wait
      - run: |
          docker run -d --rm --network host -p8080:8080 \
          -e AWS_ACCESS_KEY_ID=accessKey \
          -e AWS_SECRET_ACCESS_KEY=secretKey \
          -e REGION=local \
          -e DYNAMO_ENDPOINT=http://localhost:4569 \
          -e DYNAMO_TABLE_RUNS=runs \
          -e DYNAMO_TABLE_SANDBOXES=sandboxes \
          -e KBC_URL=https://connection.keboola.com \
          -e API_URL=http://localhost:8080 \
          -e PROVDER=aws \
          -e STAGE=dev \
          keboola.azurecr.io/sandboxes-api yarn start
      - run: |
          docker run --rm --network host \
          -e TARGETS=localhost:8080 \
          -e TIMEOUT=60 \
          waisbrot/wait
      - name: Lint code
        run: |
          docker run --rm --network host \
          keboola/sandboxes-api-php-client composer cs
      - name: Run tests
        run: |
          docker run --rm --network host \
          -e API_URL=http://localhost:8080 \
          -e AWS_ACCESS_KEY_ID=accessKey \
          -e AWS_SECRET_ACCESS_KEY=secretKey \
          -e DYNAMO_ENDPOINT=http://localhost:4569 \
          -e DYNAMO_TABLE_SANDBOXES=sandboxes \
          -e DYNAMO_TABLE_RUNS=runs \
          -e KBC_URL=https://connection.keboola.com \
          -e "KBC_STORAGE_TOKEN=${{ secrets.KBC_STORAGE_TOKEN }}" \
          -e "KBC_MANAGE_TOKEN=${{ secrets.KBC_MANAGE_TOKEN }}" \
          keboola/sandboxes-api-php-client composer test
