name: "Build"
'on':
  - push
concurrency: 'ci-${{ github.ref }}'
env:
  KBC_STORAGE_TOKEN: '${{ secrets.KBC_STORAGE_TOKEN }}'
  KBC_MANAGE_TOKEN: '${{ secrets.KBC_MANAGE_TOKEN }}'
  KBC_MANAGE_NOTIFY_TOKEN: '${{ secrets.KBC_MANAGE_NOTIFY_TOKEN }}'

  # Azure
  AZURE_CLIENT_ID: 233328da-9afe-423b-82c1-915d8c539f71
  AZURE_CLIENT_SECRET: '${{ secrets.AZURE_CLIENT_SECRET }}'
  AZURE_TENANT_ID: 9b85ee6f-4fb0-4a46-8cb7-4dcc6b262a89
  COSMOS_DB_ID: sandboxes-api
  COSMOS_ENDPOINT: https://ci-sandboxes-api-php-client.documents.azure.com:443
  COSMOS_KEY: '${{ secrets.COSMOS_KEY }}'
  KEYVAULT_KEY_NAME: sandboxes-api-key
  KEYVAULT_VAULT_NAME: sandboxes-api-ci

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - uses: azure/docker-login@v1
        with:
          login-server: keboola.azurecr.io
          username: ${{ secrets.ACR_PULL_USERNAME }}
          password: ${{ secrets.ACR_PULL_PASSWORD }}

      - run: docker pull waisbrot/wait
      - run: docker pull keboola.azurecr.io/sandboxes-api:production-44de22a31a3c33c88a1a68c647f385da77fa3913
      - run: docker build -t keboola/sandboxes-api-php-client .

      - name: Run tests
        run: |
          docker-compose run tests composer install
          docker-compose run tests composer ci
      - name: Dump docker logs on failure
        if: failure()
        run: docker-compose logs
